### ISSUE TITLE
Namerd with etcd storage on non-default port fails

### ISSUE THREAD

**Issue by OleksandrBerezianskyi** [BuoyantIO/linkerd#689]
Start Namerd with the next config
```yaml
    storage:
      kind: io.l5d.etcd
      experimental: true
      pathPrefix: /namerd/stage/dtabs
      port: 4001
```

Namerd fails to start with the next exception:
```
THREAD1: localhost:Port(4001): name resolution failed  (local dtab: Dtab())
java.lang.NumberFormatException: For input string: "Port(4001)"
at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
at java.lang.Integer.parseInt(Integer.java:580)
at java.lang.Integer.parseInt(Integer.java:615)
at scala.collection.immutable.StringLike$class.toInt(StringLike.scala:272)
at scala.collection.immutable.StringOps.toInt(StringOps.scala:30)
at com.twitter.finagle.util.InetSocketAddressUtil$$anonfun$parseHostPorts$3.apply(InetSocketAddressUtil.scala:39)
at com.twitter.finagle.util.InetSocketAddressUtil$$anonfun$parseHostPorts$3.apply(InetSocketAddressUtil.scala:35)
at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
at scala.collection.TraversableLike$class.map(TraversableLike.scala:245)
at scala.collection.mutable.ArrayOps$ofRef.map(ArrayOps.scala:186)
at com.twitter.finagle.util.InetSocketAddressUtil$.parseHostPorts(InetSocketAddressUtil.scala:35)
at com.twitter.finagle.InetResolver$$anonfun$8.apply(Resolver.scala:219)
at com.twitter.finagle.InetResolver$$anonfun$8.apply(Resolver.scala:219)
at com.twitter.util.Try$.apply(Try.scala:13)
at com.twitter.finagle.InetResolver.bind(Resolver.scala:219)
at com.twitter.finagle.BaseResolver.eval(Resolver.scala:419)
at com.twitter.finagle.BaseResolver.evalLabeled(Resolver.scala:435)
at com.twitter.finagle.Client$class.newService(Client.scala:48)
at com.twitter.finagle.Http$.newService(Http.scala:49)
at io.buoyant.namerd.storage.etcd.EtcdConfig.mkDtabStore(EtcdDtabStoreInitializer.scala:23)
at io.buoyant.namerd.NamerdConfig.mk(NamerdConfig.scala:35)
at io.buoyant.namerd.Main$.main(Main.scala:17)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at com.twitter.app.App$$anonfun$nonExitingMain$3.apply(App.scala:176)
at com.twitter.app.App$$anonfun$nonExitingMain$3.apply(App.scala:175)
at scala.Option.foreach(Option.scala:257)
at com.twitter.app.App$class.nonExitingMain(App.scala:175)
at io.buoyant.namerd.Main$.nonExitingMain(Main.scala:9)
at com.twitter.app.App$class.main(App.scala:141)
at io.buoyant.namerd.Main$.main(Main.scala:9)
at io.buoyant.namerd.Main.main(Main.scala)
```

**Comment by OleksandrBerezianskyi** [comment]
Fixed with the referenced pull
