### ISSUE TITLE
h2 reference count exceptions logged on service close

### ISSUE THREAD

**Issue by olix0r** [BuoyantIO/linkerd#739]
After calling `.close()` on a server:

```
----------------OUTBOUND--------------------
[id: 0x514f54ce, L:/192.168.42.66:49418 - R:/0.0.0.0:49417] GO_AWAY: lastStreamId=0, errorCode=0, length=0, bytes=
------------------------------------
Oct 13, 2016 5:46:55 PM io.netty.handler.codec.http2.Http2FrameLogger log
INFO: 
----------------INBOUND--------------------
[id: 0x0d2f0596, L:/192.168.42.66:49417 - R:/192.168.42.66:49418] GO_AWAY: lastStreamId=0, errorCode=0, length=0, bytes=
------------------------------------
Oct 13, 2016 5:46:55 PM io.netty.channel.DefaultChannelPipeline onUnhandledInboundException
WARNING: An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
io.netty.util.IllegalReferenceCountException: refCnt: 0, decrement: 1
    at io.netty.buffer.AbstractReferenceCountedByteBuf.release(AbstractReferenceCountedByteBuf.java:111)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:256)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:350)
    at com.twitter.finagle.netty4.channel.DirectToHeapInboundHandler$.channelRead(DirectToHeapInboundHandler.scala:23)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:350)
    at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358)
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
```

**Comment by olix0r** [comment]
no longer true
