### ISSUE TITLE
Namerd not recognizing io.l5d.zkLeader

### ISSUE THREAD

**Issue by JustinVenus** [BuoyantIO/linkerd#747]
I've been experimenting with namerd and it seems that it doesn't recognize zkLeader as a valid namer.  Did I miss something?  I thought namerd supported all namers that linkerd supports.

here is my failure
```sh
Oct 14, 2016 3:10:38 PM com.twitter.finagle.http.HttpMuxer$$anonfun$4 apply
INFO: HttpMuxer[/admin/metrics.json] = com.twitter.finagle.stats.MetricsExporter(<function1>)
Oct 14, 2016 3:10:38 PM com.twitter.finagle.http.HttpMuxer$$anonfun$4 apply
INFO: HttpMuxer[/admin/per_host_metrics.json] = com.twitter.finagle.stats.HostMetricsExporter(<function1>)
com.fasterxml.jackson.databind.JsonMappingException: Could not resolve type id 'io.l5d.zkLeader' into a subtype of [simple type, class io.buoyant.namer.NamerConfig]: known type ids = [NamerConfig, io.l5d.consul, io.l5d.fs, io.l5d.k8s, io.l5d.marathon, io.l5d.serversets]
 at [Source: java.io.StringReader@1e636ea3; line: 38, column: 9] (through reference chain: io.buoyant.namerd.NamerdConfig["namers"]->com.fasterxml.jackson.module.scala.deser.BuilderWrapper[0])
	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:148)
	at com.fasterxml.jackson.databind.DeserializationContext.unknownTypeException(DeserializationContext.java:967)
	at com.fasterxml.jackson.databind.jsontype.impl.TypeDeserializerBase._handleUnknownTypeId(TypeDeserializerBase.java:277)
	at com.fasterxml.jackson.databind.jsontype.impl.TypeDeserializerBase._findDeserializer(TypeDeserializerBase.java:159)
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer._deserializeTypedForId(AsPropertyTypeDeserializer.java:108)
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromObject(AsPropertyTypeDeserializer.java:93)
	at com.fasterxml.jackson.databind.deser.AbstractDeserializer.deserializeWithType(AbstractDeserializer.java:131)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:247)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:217)
	at com.fasterxml.jackson.module.scala.deser.SeqDeserializer.deserialize(SeqDeserializerModule.scala:76)
	at com.fasterxml.jackson.module.scala.deser.SeqDeserializer.deserialize(SeqDeserializerModule.scala:59)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:520)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:463)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:378)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1099)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:296)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:133)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3736)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2764)
	at com.fasterxml.jackson.module.scala.experimental.ScalaObjectMapper$class.readValue(ScalaObjectMapper.scala:184)
	at io.buoyant.config.Parser$$anon$1.readValue(Parser.scala:71)
	at io.buoyant.namerd.NamerdConfig$.loadNamerd(NamerdConfig.scala:95)
	at io.buoyant.namerd.NamerdConfig$.loadNamerd(NamerdConfig.scala:99)
	at io.buoyant.namerd.Main$.loadNamerd(Main.scala:49)
	at io.buoyant.namerd.Main$.main(Main.scala:16)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.twitter.app.App$$anonfun$nonExitingMain$3.apply(App.scala:176)
	at com.twitter.app.App$$anonfun$nonExitingMain$3.apply(App.scala:175)
	at scala.Option.foreach(Option.scala:257)
	at com.twitter.app.App$class.nonExitingMain(App.scala:175)
	at io.buoyant.namerd.Main$.nonExitingMain(Main.scala:9)
	at com.twitter.app.App$class.main(App.scala:141)
	at io.buoyant.namerd.Main$.main(Main.scala:9)
	at io.buoyant.namerd.Main.main(Main.scala)
Exception thrown in main on startup
```

here is the namer section of the config
```yaml
namers:
- kind: io.l5d.consul
  experimental: true
  includeTag: true
  useHealthCheck: true
  host: localhost
  port: 8500
- kind: io.l5d.serversets
  zkAddrs:
  - host: mesos-master01of2
    port: 2181
  - host: mesos-master02of2
    port: 2181
  - host: mesos-master03of2
    port: 2181
- kind: io.l5d.zkLeader
  zkAddrs:
  - host: mesos-master01of2
    port: 2181
  - host: mesos-master02of2
    port: 2181
  - host: mesos-master03of2
    port: 2181
interfaces:
- kind: io.l5d.thriftNameInterpreter
  port: 31566
  ip: 0.0.0.0
  retryBaseSecs:  600
  retryJitterSecs: 60
- kind: io.l5d.httpController
  port: 31935
  ip: 0.0.0.0
```

**Comment by JustinVenus** [comment]
I missed the `experimental` kv :(

**Comment by JustinVenus** [comment]
Ok, sorry for the spam `experimental` has no effect.

```sh
Oct 14, 2016 3:19:15 PM com.twitter.finagle.http.HttpMuxer$$anonfun$4 apply
INFO: HttpMuxer[/admin/metrics.json] = com.twitter.finagle.stats.MetricsExporter(<function1>)
Oct 14, 2016 3:19:15 PM com.twitter.finagle.http.HttpMuxer$$anonfun$4 apply
INFO: HttpMuxer[/admin/per_host_metrics.json] = com.twitter.finagle.stats.HostMetricsExporter(<function1>)
com.fasterxml.jackson.databind.JsonMappingException: Could not resolve type id 'io.l5d.zkLeader' into a subtype of [simple type, class io.buoyant.namer.NamerConfig]: known type ids = [NamerConfig, io.l5d.consul, io.l5d.fs, io.l5d.k8s, io.l5d.marathon, io.l5d.serversets]
 at [Source: java.io.StringReader@1e636ea3; line: 38, column: 9] (through reference chain: io.buoyant.namerd.NamerdConfig["namers"]->com.fasterxml.jackson.module.scala.deser.BuilderWrapper[0])
	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:148)
	at com.fasterxml.jackson.databind.DeserializationContext.unknownTypeException(DeserializationContext.java:967)
	at com.fasterxml.jackson.databind.jsontype.impl.TypeDeserializerBase._handleUnknownTypeId(TypeDeserializerBase.java:277)
	at com.fasterxml.jackson.databind.jsontype.impl.TypeDeserializerBase._findDeserializer(TypeDeserializerBase.java:159)
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer._deserializeTypedForId(AsPropertyTypeDeserializer.java:108)
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromObject(AsPropertyTypeDeserializer.java:93)
	at com.fasterxml.jackson.databind.deser.AbstractDeserializer.deserializeWithType(AbstractDeserializer.java:131)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:247)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:217)
	at com.fasterxml.jackson.module.scala.deser.SeqDeserializer.deserialize(SeqDeserializerModule.scala:76)
	at com.fasterxml.jackson.module.scala.deser.SeqDeserializer.deserialize(SeqDeserializerModule.scala:59)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:520)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:463)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:378)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1099)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:296)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:133)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3736)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2764)
	at com.fasterxml.jackson.module.scala.experimental.ScalaObjectMapper$class.readValue(ScalaObjectMapper.scala:184)
	at io.buoyant.config.Parser$$anon$1.readValue(Parser.scala:71)
	at io.buoyant.namerd.NamerdConfig$.loadNamerd(NamerdConfig.scala:95)
	at io.buoyant.namerd.NamerdConfig$.loadNamerd(NamerdConfig.scala:99)
	at io.buoyant.namerd.Main$.loadNamerd(Main.scala:49)
	at io.buoyant.namerd.Main$.main(Main.scala:16)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.twitter.app.App$$anonfun$nonExitingMain$3.apply(App.scala:176)
	at com.twitter.app.App$$anonfun$nonExitingMain$3.apply(App.scala:175)
	at scala.Option.foreach(Option.scala:257)
	at com.twitter.app.App$class.nonExitingMain(App.scala:175)
	at io.buoyant.namerd.Main$.nonExitingMain(Main.scala:9)
	at com.twitter.app.App$class.main(App.scala:141)
	at io.buoyant.namerd.Main$.main(Main.scala:9)
	at io.buoyant.namerd.Main.main(Main.scala)
Exception thrown in main on startup
```

**Comment by JustinVenus** [comment]
I may have a fix ... i'm compiling namerd atm

**Comment by JustinVenus** [comment]
PR https://github.com/BuoyantIO/linkerd/pull/755 should address this issue.

**Comment by JustinVenus** [comment]
Fixed.
