### ISSUE TITLE
DCOS Universe Package Fails to install on DCOS Centos based templates

### ISSUE THREAD

**Issue by camechis** [BuoyantIO/linkerd#774]
Installing Linkerd fails to install on DCOS 1.8.6 that is setup via the AWS Centos DCOS cloudformation templates ( https://dcos.io/docs/1.8/administration/installing/cloud/aws/advanced/template-reference/ ).

The mesos containers fail to start with an Unknown Host Exception

``````
I 1026 20:17:35.007 THREAD1: Resolver[flag] = com.twitter.server.FlagResolver(com.twitter.server.FlagResolver@16134a1)
java.net.UnknownHostException: ip-10-0-63-225: ip-10-0-63-225: unknown error
    at java.net.InetAddress.getLocalHost(InetAddress.java:1505)
    at io.buoyant.transformer.perHost.LocalhostTransformerConfig.mk(LocalhostTransformerInitializer.scala:15)
    at io.buoyant.namer.InterpreterConfig$$anonfun$interpreter$1.apply(InterpreterInitializer.scala:21)
    at io.buoyant.namer.InterpreterConfig$$anonfun$interpreter$1.apply(InterpreterInitializer.scala:20)
    at scala.collection.LinearSeqOptimized$class.foldLeft(LinearSeqOptimized.scala:124)
    at scala.collection.immutable.List.foldLeft(List.scala:84)
    at io.buoyant.namer.InterpreterConfig$class.interpreter(InterpreterInitializer.scala:20)
    at io.buoyant.namer.DefaultInterpreterConfig.interpreter(DefaultInterpreterInitializer.scala:15)
    at io.buoyant.linkerd.Linker$LinkerConfig$$anonfun$7.apply(Linker.scala:167)
    at io.buoyant.linkerd.Linker$LinkerConfig$$anonfun$7.apply(Linker.scala:166)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
    at scala.collection.immutable.List.foreach(List.scala:381)
    at scala.collection.TraversableLike$class.map(TraversableLike.scala:245)
    at scala.collection.immutable.List.map(List.scala:285)
    at io.buoyant.linkerd.Linker$LinkerConfig.mkRouters(Linker.scala:166)
    at io.buoyant.linkerd.Linker$LinkerConfig.mk(Linker.scala:122)
    at io.buoyant.linkerd.Main$.main(Main.scala:33)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.twitter.app.App$$anonfun$nonExitingMain$3.apply(App.scala:176)
    at com.twitter.app.App$$anonfun$nonExitingMain$3.apply(App.scala:175)
    at scala.Option.foreach(Option.scala:257)
    at com.twitter.app.App$class.nonExitingMain(App.scala:175)
    at io.buoyant.linkerd.Main$.nonExitingMain(Main.scala:19)
    at com.twitter.app.App$class.main(App.scala:141)
    at io.buoyant.linkerd.Main$.main(Main.scala:19)
    at io.buoyant.linkerd.Main.main(Main.scala)
Caused by: java.net.UnknownHostException: ip-10-0-63-225: unknown error
    at java.net.Inet4AddressImpl.lookupAllHostAddr(Native Method)
    at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:928)
    at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1323)
    at java.net.InetAddress.getLocalHost(InetAddress.java:1500)
    ... 29 moreI 1026 20:17:35.007 THREAD1: Resolver[flag] = com.twitter.server.FlagResolver(com.twitter.server.FlagResolver@16134a1)
java.net.UnknownHostException: ip-10-0-63-225: ip-10-0-63-225: unknown error
    at java.net.InetAddress.getLocalHost(InetAddress.java:1505)
    at io.buoyant.transformer.perHost.LocalhostTransformerConfig.mk(LocalhostTransformerInitializer.scala:15)
    at io.buoyant.namer.InterpreterConfig$$anonfun$interpreter$1.apply(InterpreterInitializer.scala:21)
    at io.buoyant.namer.InterpreterConfig$$anonfun$interpreter$1.apply(InterpreterInitializer.scala:20)
    at scala.collection.LinearSeqOptimized$class.foldLeft(LinearSeqOptimized.scala:124)
    at scala.collection.immutable.List.foldLeft(List.scala:84)
    at io.buoyant.namer.InterpreterConfig$class.interpreter(InterpreterInitializer.scala:20)
    at io.buoyant.namer.DefaultInterpreterConfig.interpreter(DefaultInterpreterInitializer.scala:15)
    at io.buoyant.linkerd.Linker$LinkerConfig$$anonfun$7.apply(Linker.scala:167)
    at io.buoyant.linkerd.Linker$LinkerConfig$$anonfun$7.apply(Linker.scala:166)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
    at scala.collection.immutable.List.foreach(List.scala:381)
    at scala.collection.TraversableLike$class.map(TraversableLike.scala:245)
    at scala.collection.immutable.List.map(List.scala:285)
    at io.buoyant.linkerd.Linker$LinkerConfig.mkRouters(Linker.scala:166)
    at io.buoyant.linkerd.Linker$LinkerConfig.mk(Linker.scala:122)
    at io.buoyant.linkerd.Main$.main(Main.scala:33)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.twitter.app.App$$anonfun$nonExitingMain$3.apply(App.scala:176)
    at com.twitter.app.App$$anonfun$nonExitingMain$3.apply(App.scala:175)
    at scala.Option.foreach(Option.scala:257)
    at com.twitter.app.App$class.nonExitingMain(App.scala:175)
    at io.buoyant.linkerd.Main$.nonExitingMain(Main.scala:19)
    at com.twitter.app.App$class.main(App.scala:141)
    at io.buoyant.linkerd.Main$.main(Main.scala:19)
    at io.buoyant.linkerd.Main.main(Main.scala)
Caused by: java.net.UnknownHostException: ip-10-0-63-225: unknown error
    at java.net.Inet4AddressImpl.lookupAllHostAddr(Native Method)
    at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:928)
    at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1323)
    at java.net.InetAddress.getLocalHost(InetAddress.java:1500)
    ... 29 more```
``````

**Comment by siggy** [comment]
The difference between the CoreOS and CentOS images seems to be the `hostname` value.

#### CoreOS

```bash
$ hostname
ip-10-0-3-101.us-west-1.compute.internal

$ nslookup ip-10-0-3-101.us-west-1.compute.internal
Server:		198.51.100.1
Address:	198.51.100.1#53

Non-authoritative answer:
Name:	ip-10-0-3-101.us-west-1.compute.internal
Address: 10.0.3.101
```

#### CentOS

```bash
$ hostname
ip-10-0-3-101

$ nslookup ip-10-0-3-101
Server:		198.51.100.1
Address:	198.51.100.1#53

** server can't find ip-10-0-3-101: NXDOMAIN
```

**Comment by camechis** [comment]
Definitely looks like its It.  Is this fixable via Linkerd or should I
contact the mesophere guys?

**Comment by siggy** [comment]
@camechis. this is a linkerd issue, not mesosphere. we're investigating a few approaches to fix this.

**Comment by olix0r** [comment]
Do we know what the linkerd issue is?

**Comment by siggy** [comment]
I believe it's this line:
https://github.com/BuoyantIO/linkerd/blob/master/interpreter/per-host/src/main/scala/io/buoyant/transformer/perHost/LocalhostTransformerInitializer.scala#L15
... interacting with my `hostname` comment above.

**Comment by olix0r** [comment]
So the issue is that the output of `hostname` is not resolvable on the host?  That sounds like a misconfigured host.   What can linkerd do to fix this?

**Comment by olix0r** [comment]
Oh right I'm recalling now, we could potentially enumerate all of the local interfaces and try to match against that, but this requires a taking a pretty different approach to this transformer.

It sounds fairly broken to me that `dig +short $(hostname)` should ever fail...

**Comment by olix0r** [comment]
And after discussing this a bit with one of the DCOS people, I'm reminded that DNS is just crazy and we should really really do everything we can to avoid relying on it for this sort of discovery.

I'm told that marathon exports a HOST environment variable containing the IP, but this isn't a very robust solution for linkerd.  I think we should pursue the interface-driven approach.

**Comment by bflance** [comment]
Hi Guys,

is there any simple guide for a beginner on how to install this on DC/OS 1.8.6?
the included linkerd 0.8.1 simply doesnt work (after installing from universe)..

a short video on youtube could really be helpful..

thanx

**Comment by siggy** [comment]
@bflance: mind providing a bit more detail? best to drop into linkerd slack. http://slack.linkerd.io

**Comment by wmorgan** [comment]
Hi @bflance!

The instructions in https://blog.buoyant.io/2016/10/10/linkerd-on-dcos-for-service-discovery-and-visibility/ should walk you through the steps for installing linkerd on DC/OS.

If you have problems following those instructions, please feel free to hop into the [Slack channel](https://slack.linkerd.io) or to file a Github issue. Be sure to include the error messages you're seeing so that we can help you diagnose the problems!

**Comment by neethugeorge** [comment]
Hi Guys,

I am facing the same issue with coreos on AWS. The containers fail to start with following exception:

```java.net.UnknownHostException: ip-10-x-x-xx.ap-southeast-1.compute.internal: ip-10-x-x-xx.ap-southeast-1.compute.internal: unknown error```

Is there any work around for this issue?

Thanks

**Comment by siggy** [comment]
Greetings @neethugeorge!

A few things:
- try a simpler linkerd config: https://github.com/BuoyantIO/linkerd-examples/tree/master/dcos/simple-proxy
- is there any additional stack trace / messages? if so pass them on.
- try our [slack channel](http://slack.linkerd.io), you'll probably get a faster response

**Comment by neethugeorge** [comment]
Thank you @siggy !

I tried with  https://github.com/BuoyantIO/linkerd-examples/tree/master/dcos/simple-proxy , and its working fine.
