### ISSUE TITLE
gRPC interop: unknown service returns with incorrect UNIMPLEMENTED code

### ISSUE THREAD

**Issue by stevej** [BuoyantIO/linkerd#890]
This from running the grpc interop tests with a grpc-java client and server through l5d

```
Running test unimplemented_method
Test completed.
Shutting down
Jan 05, 2017 8:48:37 PM io.grpc.internal.ManagedChannelImpl <init>
INFO: [io.grpc.internal.ManagedChannelImpl-1] Created with target directaddress:///proxy-test-4b/10.240.0.10:
4141
Running test unimplemented_service
Exception in thread "main" java.lang.AssertionError: expected:<UNIMPLEMENTED> but was:<UNAVAILABLE>
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.failNotEquals(Assert.java:743)
        at org.junit.Assert.assertEquals(Assert.java:118)
        at org.junit.Assert.assertEquals(Assert.java:144)
        at io.grpc.testing.integration.AbstractInteropTest.unimplementedService(AbstractInteropTest.java:999)
        at io.grpc.testing.integration.TestServiceClient.runTest(TestServiceClient.java:282)
        at io.grpc.testing.integration.TestServiceClient.run(TestServiceClient.java:200)
        at io.grpc.testing.integration.TestServiceClient.main(TestServiceClient.java:84)
Shutting down
```

This test calls a service that isn't implemented in the server.

According to Section 7 of the gRPC I-D, we should check that we map the following Transport error: HTTP/2 REFUSED_STREAM to gRPC UNAVAILABLE.

**Comment by stevej** [comment]
When l5d is setup to route all gRPC requests to the correct gRPC backend, this succeeds.

```
$ ./bin/test-client --server_host=proxy-test-4b --server_port=4141 --use_tls=false --test_case=unimplemented_service
Jan 11, 2017 9:19:32 PM io.grpc.internal.ManagedChannelImpl <init>
INFO: [io.grpc.internal.ManagedChannelImpl-1] Created with target directaddress:///proxy-test-4b/10.240.0.10:4141
Running test unimplemented_service
Test completed.
Shutting down
```

For reference, here's the config file I was using with linkerd to test this
```
routers:

- protocol: h2
  experimental: true
  label: h2c
  servers:
  - port: 4141
    ip: 0.0.0.0
  dstPrefix: /grpc
  identifier:
    kind: io.l5d.headerPath
  baseDtab: |
    /srv => /$/inet/10.240.0.4/8080;
    /grpc => /srv;
```
