### ISSUE TITLE
gRPC interop: compute_engine_creds test fails

### ISSUE THREAD

**Issue by stevej** [BuoyantIO/linkerd#895]
```
Jan 05, 2017 8:48:33 PM io.grpc.internal.ManagedChannelImpl <init>
INFO: [io.grpc.internal.ManagedChannelImpl-1] Created with target directaddress:///proxy-test-4b/10.240.0.10:
4141
Running test compute_engine_creds
Exception in thread "main" java.lang.AssertionError: expected:<null> but was:<>
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.failNotEquals(Assert.java:743)
        at org.junit.Assert.assertEquals(Assert.java:118)
        at org.junit.Assert.assertEquals(Assert.java:144)
        at io.grpc.testing.integration.AbstractInteropTest.computeEngineCreds(AbstractInteropTest.java:1091)
        at io.grpc.testing.integration.TestServiceClient.runTest(TestServiceClient.java:236)
        at io.grpc.testing.integration.TestServiceClient.run(TestServiceClient.java:200)
        at io.grpc.testing.integration.TestServiceClient.main(TestServiceClient.java:84)
Shutting down
```

**Comment by stevej** [comment]
it's worth noting that gRPC won't send credentials over an unencrypted channel and this test was done without TLS so I will re-run all of these credential failure test cases with TLS.
